[project]
name = "dlc-image-labeler"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.7",
    "pyyaml>=6.0.3",
    "scipy>=1.16.2",
]
